In [5]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(PROJECT_ROOT / "src"))

print("PROJECT_ROOT =", PROJECT_ROOT)

PROJECT_ROOT = c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator

In [6]:
from config import RAW_CSV_PATH, CLEANED_DATA_PATH
from data_utils import load_and_clean_dataset

In [7]:
df = load_and_clean_dataset(RAW_CSV_PATH)
print("Shape:", df.shape)
df.head()

Shape: (780, 11)

,pos,main_category,subcategory,target_word,cue_text,score_lin,score_wang,score_chiu,score_mean,score_std,cue_length_chars
0,名詞,日常飲食,水果,蘋果,一種紅色圓形的水果,2.0,1.0,1.0,1.333333,0.577350,9
1,名詞,日常飲食,水果,蘋果,富士山盛產的水果,6.0,3.0,2.0,3.666667,2.081666,8
2,名詞,日常飲食,水果,蘋果,"一日一XX,醫生遠離我",4.0,2.0,6.0,4.000000,2.000000,11
3,名詞,日常飲食,水果,蘋果,媽媽用刀子削XX,3.0,6.0,4.0,4.333333,1.527525,8
4,名詞,日常飲食,水果,蘋果,我去菜市場買一顆XX,1.0,4.0,3.0,2.666667,1.527525,10

In [8]:
category_summary = (
    df.groupby(["main_category", "subcategory"])["target_word"]
    .nunique()
    .reset_index(name="unique_words")
    .sort_values(["main_category", "unique_words"], ascending=[True, False])
)
category_summary.head(50)

   main_category subcategory  unique_words
1             地點        娛樂場所             2
3             地點        購物場所             2
4             地點        運動場所             2
5             地點        醫療場所             2
0             地點        交通場所             1
2             地點          學校             1
6             地點        金融機構             1
7           日常活動        休閒娛樂            10
8           日常行為          動作            25
17          日常起居        電器用品            16
14          日常起居        生活用品             8
9           日常起居        交通工具             6
16          日常起居          輔具             6
10          日常起居          家具             4
11          日常起居        廚房用品             3
13          日常起居       服飾&配件             3
18          日常起居          餐具             3
15          日常起居          調味             2
12          日常起居          文具             1
22          日常飲食          食物            16
20          日常飲食          水果             6
19          日常飲食           喝             3
21          日常飲食          蔬菜             2
23          自然環境          動物             5

In [9]:
df.to_csv(CLEANED_DATA_PATH, index=False, encoding="utf-8-sig")
print("Saved:", CLEANED_DATA_PATH)

Saved: c:\Users\804\Dtx_Projects\Aphasia_APE_Cue_Generator\data\interim\cleaned_dataset.csv